---

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.2.0
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml

tox:
  stage: test
  image: ${BASE_CONTAINER_REGISTRY}/python3.6-builder
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  tags:
    - dind
  variables:
    BASE_CONTAINER_VERSION: 2.3.1
    # these are for postgres docker
    POSTGRES_DB: automated_test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
  before_script:
    - !reference [.load_github_key, script]
    - pip install "tox<4"
  script:
    - tox -r -e py


# used by release
.python_versions:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [python3.6]
      - RELEASE_PY_VERSION: [python3.6]

release:
  before_script:
    - git fetch --unshallow || true
  variables:
    LEGACY_BASE_CONTAINER_VERSION: 2.3.0
