---
stages:
  - .pre
  - test
  - build
  - trigger

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.2.0
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml

tox:
  stage: test
  image: ${BASE_CONTAINER_REGISTRY}/python3.6-builder
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  tags:
    - dind
  variables:
    BASE_CONTAINER_VERSION: 2.3.1
    # these are for postgres docker
    POSTGRES_DB: automated_test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
    PG_HOST: postgres
  before_script:
    - !reference [.load_github_key, script]
    - pip install "tox<4"
  script:
    - tox -r -e py


# used by release
.python_versions:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [python3.6]
      - RELEASE_PY_VERSION: [python3.6]

release:
  variables:
    RELEASE_PY_VERSION: python3.7
    GIT_DEPTH: 0
  after_script:
    - pip install --no-deps -e .
    - python -c "import importlib.metadata; print(importlib.metadata.version('inspector'))"
      | tee VERSION.txt
  artifacts:
    paths:
      - VERSION.txt
    expire_in: 1 week

trigger_inspector:
  stage: trigger
  script:
    - apk add --no-cache curl
    - VERSION=$(cat VERSION.txt)
    - >
      curl --fail --request POST
      --form token=$CI_JOB_TOKEN
      --form ref=${CI_TRIGGERED_BRANCH:=feat/dev-2303-downstream-pipeline}
      --form variables[CI_TRIGGER_VERSION]=$VERSION
      --form variables[CI_TRIGGER_REPO]=$CI_PROJECT_NAME
      "https://gitlab.datacommons.io/api/v4/projects/22/trigger/pipeline"
    - echo $$CI_COMMIT_REF_NAME
    - echo $CI_TRIGGER_VERSION
  rules:
    - when: manual
