---

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.4.0
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml

tox:
  parallel:
    matrix:
      - BUILD_PY_VERSION:
          - python3.7
          - python3.8
          - python3.9
          - python3.10
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  variables:
    BASE_CONTAINER_VERSION: 2.3.1
    # these are for postgres docker
    POSTGRES_DB: automated_test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
    PG_HOST: postgres
  script:
    - tox -r -e py


release:
  variables:
    RELEASE_PY_VERSION: python3.7
    GIT_DEPTH: 0
