---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml

variables:
  TWINE_USERNAME: ${TWINE_USER}
  TWINE_PASSWORD: ${TWINE_PASSWORD}
  TWINE_REPOSITORY_URL: https://nexus.osdc.io/repository/pypi-snapshots/

pre-commit:
  stage: .pre
  image: ${BASE_CONTAINER_REGISTRY}/python3.7-builder
  before_script:
    - pip install 'tox < 4'
  script:
    - tox -e lint

tests:py37:
  stage: test
  needs:
    - pre-commit
  image: ${BASE_CONTAINER_REGISTRY}/python3.7-builder
  tags:
    - dind
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:2.2.0
      alias: postgres
  variables:
    POSTGRES_DB: ${DB_NAME}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_HOST_AUTH_METHOD: trust
  before_script:
    - pip install 'tox < 4'
  script:
    - tox -e py37
