---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

variables:
  PRE_COMMIT_DOCKER_IMAGE: ${BASE_CONTAINER_REGISTRY}/python3.8-builder
  PRE_COMMIT_VERSION: 3.2.1
  TWINE_USERNAME: ${TWINE_USER}
  TWINE_PASSWORD: ${TWINE_PASSWORD}
  TWINE_REPOSITORY_URL: https://nexus.osdc.io/repository/pypi-snapshots/

tox:
  stage: test
  parallel:
    matrix:
      - PY_VER:
          - '3.6'
          - '3.7'
          - '3.8'
  needs:
    - pre-commit
  image: ${BASE_CONTAINER_REGISTRY}/python${PY_VER}-builder
  tags:
    - dind
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:2.2.0
      alias: postgres
  variables:
    PG_HOST: postgres
    POSTGRES_DB: ${DB_NAME}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_HOST_AUTH_METHOD: trust
  before_script:
    - pip install 'tox < 4'
  script:
    - tox -e py
