---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml

stages:
  - build
  - test
  - deploy

variables:
  TWINE_USERNAME: ${TWINE_USER}
  TWINE_PASSWORD: ${TWINE_PASSWORD}
  TWINE_REPOSITORY_URL: https://nexus.osdc.io/repository/pypi-snapshots/

default:
  image: python:3.8
  before_script:
    - export PATH=~/.local/bin:$PATH
    - echo $PATH
    - apt-get update && apt-get install -y python3-pip python3-venv
    - /usr/bin/python3 -m pip install pipx
    - pipx install poetry~=1.4.0
    - pipx install tox

build:
  stage: build
  script:
    - tox -e build
  artifacts:
    paths:
      - dist/

.test:
  stage: test
  variables:
    PY_PATTERN: s/Python \([0-9]\+\).\([0-9]\+\).[0-9]\+/py\1\2/
    POSTGRES_DB: automated_test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
  services:
    - postgres:13
  script:
    - poetry install --with test
    - poetry run setup-test --host postgres
    - tox -e gitlab-$(python -V | sed "$PY_PATTERN")
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: .test-reports/coverage.xml

test 3.6:
  extends: .test
  image: python:3.6

test 3.7:
  extends: .test
  image: python:3.7

test 3.8:
  extends: .test
  image: python:3.8

test 3.9:
  extends: .test
  image: python:3.9

test 3.10:
  extends: .test
  image: python:3.10

test 3.11:
  extends: .test
  image: python:3.11

test 3.12:
  extends: .test
  image: python:3.12-rc
  allow_failure: true
