---
stages:
  - .pre
  - test
  - build
  - stage_trigger

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.4.0
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml

tox:
  parallel:
    matrix:
      - BUILD_PY_VERSION:
          - python3.7
          - python3.8
          - python3.9
          - python3.10
          - python3.11
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  variables:
    BASE_CONTAINER_VERSION: 2.3.1
    # these are for postgres docker
    POSTGRES_DB: automated_test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
    PG_HOST: postgres
  script:
    - tox -r -e py


release:
  variables:
    RELEASE_PY_VERSION: python3.7
    GIT_DEPTH: 0
  after_script:
    - pip install "setuptools_scm>=6.2,<8" "setuptools-git-versioning<2"
    - python -m setuptools_git_versioning | tee VERSION.txt
  artifacts:
    paths:
      - VERSION.txt
    expire_in: 1 week

.downstream_repos:
  parallel:
    matrix:
      - TRIGGERED_REPO: 29
        NAME: inspector
      - TRIGGERED_REPO: 7
        NAME: gdcapi
      - TRIGGERED_REPO: 122
        NAME: sheepdog
      - TRIGGERED_REPO: 79
        NAME: esbuild
      - TRIGGERED_REPO: 30
        NAME: graphmanager
      - TRIGGERED_REPO: 76
        NAME: gdcadmin

trigger:
  stage: stage_trigger
  dependencies:
    - release
  parallel: !reference [.downstream_repos, parallel]
  script:
    - apk add --no-cache curl
    - VERSION=$(cat VERSION.txt)
    - echo $VERSION
    - >
      curl --fail --request POST
      --form token=$CI_JOB_TOKEN
      --form ref=${CI_TRIGGERED_BRANCH:=develop}
      --form variables[CI_TRIGGER_VERSION]=$VERSION
      --form variables[CI_TRIGGER_REPO]=$CI_PROJECT_NAME
      --form variables[CI_TRIGGER_BRANCH]=$CI_COMMIT_REF_NAME
      --form variables[CI_TRIGGER_TAG]=$CI_COMMIT_TAG
      "https://gitlab.datacommons.io/api/v4/projects/$TRIGGERED_REPO/trigger/pipeline"
  when: manual

trigger_pre_release:
  stage: stage_trigger
  parallel: !reference [.downstream_repos, parallel]
  script:
    - apk add --no-cache curl
    - >
      curl --fail --request POST
      --form token=$CI_JOB_TOKEN
      --form ref=${CI_TRIGGERED_BRANCH:=develop}
      --form variables[PRE_RELEASE_STAGE]=${PRE_RELEASE_STAGE:-alpha}
      "https://gitlab.datacommons.io/api/v4/projects/$TRIGGERED_REPO/trigger/pipeline"
  when: manual

trigger_branch_pattern:
  stage: stage_trigger
  parallel: !reference [.downstream_repos, parallel]
  script:
    - apk add --no-cache curl
    - >
      curl --fail --request POST
      --form token=$CI_JOB_TOKEN
      --form ref=${CI_TRIGGERED_BRANCH:=develop}
      --form variables[BRANCH_PATTERN]=${BRANCH_PATTER:-${CI_COMMIT_REF_SLUG//_/.}}
      "https://gitlab.datacommons.io/api/v4/projects/$TRIGGERED_REPO/trigger/pipeline"
  when: manual
