repos:
  - repo: git@github.com:Yelp/detect-secrets
    rev: v0.13.1
    hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline' ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [ --remove ]
      - id: check-yaml
  - repo: https://github.com/pycqa/isort
    rev: 4.3.21
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [ cython ]
      - id: isort
        name: isort (pyi)
        types: [ pyi ]
