[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=68", "wheel", "setuptools_scm[toml]>=7.0", "versionista>=1.1.0"]

[project]
authors = [{name = "NCI GDC", email = "support@nci-gdc.datacommons.io"}]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: Unix",
  "Operating System :: POSIX :: Linux",
  "Topic :: Internet",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Development Status   :: 5 - Production/Stable"
]
dependencies = [
  "more-itertools",
  "psycopg2",
  "rstr",
  "sqlalchemy~=1.4",
  "typing-extensions",
  "xlocal"
]
description = "postgresql graph library"
dynamic = ["version"]
keywords = ["psqlgraph", "sqlalchemy", "Genomic Data Commons", "graph databases"]
license = {file = "LICENSE"}
name = "psqlgraph"
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["coverage[toml]", "pytest", "pytest-cov>=2.7.1"]
lint = ["mypy", "pre-commit"]

[project.urls]
repository = "https://github.com/NCI-GDC/psqlgraph"

[tool.coverage.html]
directory = "docs/htmlcov"
show_contexts = true
title = "psqlgraph coverage report"

[tool.coverage.run]
branch = true
context = "unit tests"
source = ["psqlgraph"]

[tool.pytest.ini_options]
minversion = "6.0"
# Silence warning by opting in to use pytest 6's new default value
addopts = "-rfE --color=yes --cov=psqlgraph --cov-report term"
console_output_style = "classic"
junit_family = "xunit2"
junit_logging = "system-out"
log_cli = true
log_cli_level = "INFO"
norecursedirs = [".git", ".tox", "dist", "build", "doc", "docs", "travis"]
testpaths = ["test"]

[tool.ruff]
line-length = 95
src = ["src", "tests"]
target-version = "py310"

[tool.ruff.lint]
# see https://docs.astral.sh/ruff/rules/
select = [
  "E", # pydocstyle errors
  "F", # pyflakes
  "I", # isort
  "N", # pep8 naming
  "RUF", # ruff specific rules
  "UP", # pyupgrade
  "W" # pydocstyle warnings
]

[tool.setuptools_scm]
local_scheme = "versionista-local-format"
version_scheme = "versionista-format"

[tool.tox]
env_list = ["py310", "py311", "py312", "py313", "py314"]
skip_missing_interpreters = true
isolated_build = true

[tool.tox.env_run_base]
usedevelop = true
extras = ["dev"]
passenv = ["PG_*"]
set_env = {SQLALCHEMY_WARN_20 = "1"}
commands = [
  [
    "python",
    "-m",
    "pytest",
    "-lv",
    {replace = "posargs", default = [
      "--cov-report=html",
      "--cov-report=xml",
      "--junit-xml=report.xml"
    ], extend = true}
  ]
]
