class PSQLGraphError(Exception): ...
class QueryError(PSQLGraphError): ...
class ProgrammingError(PSQLGraphError): ...
class NodeCreationError(PSQLGraphError): ...
class EdgeCreationError(PSQLGraphError): ...
class ValidationError(PSQLGraphError): ...
class SessionClosedError(PSQLGraphError): ...
