from typing import Any, Dict, Iterable, Tuple

from psqlgraph import attributes

def history(target: Any, column: Any, attr: str) -> Dict[str, Any]: ...
def get_old_version(
    target: Any, *attrs: str
) -> Tuple[attributes.PropertiesDict, attributes.SystemAnnotationDict]: ...
def is_psqlgraph_entity(target: Any) -> bool: ...
def receive_before_flush(
    session: Any, flush_context: Any, instances: Iterable[Any]
) -> None: ...
